# Generated by Django 3.2.3 on 2021-05-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBS_debt', models.IntegerField()),
                ('client_score', models.IntegerField(choices=[(1, 'Bad'), (2, 'Regular'), (3, 'Good')])),
                ('sentinel_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('approvement', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
