# Generated by Django 3.2.3 on 2021-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_score',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sentinel_score',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Regular'), (3, 'Good')]),
        ),
    ]
